services:
  aimodels-prices:
    container_name: aimodels-prices
    image: ghcr.io/woodchen-ink/aimodels-prices:latest
    restart: always
    environment:
      - GIN_MODE=release
      - PORT=8080
      - TZ=Asia/Shanghai
      # 飞书Webhook配置（可选）
      # - FEISHU_WEBHOOK_URL=https://open.feishu.cn/open-apis/bot/v2/hook/your-webhook-url
    volumes:
      - ./data:/app/data
    ports:
      - 10124:8080
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
