services:
  aimodels-prices:
    container_name: aimodels-prices
    image: woodchen/aimodels-prices:latest
    restart: always
    environment:
      - GIN_MODE=release
      - PORT=8080
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
    ports:
      - 10124:80
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
